# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realfagsappen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Realfagsappen
  pod 'Google-Mobile-Ads-SDK'

  # Pods for Realfagsappen
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'RealfagsappenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

